spring:
  datasource:
    url: jdbc:mysql://10.0.0.5:3306/notice?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: dhwlrthfdl19!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace
  org.springframework.web: DEBUG
  org.springframework.web.servlet.mvc.method.annotation: TRACE

spring.thymeleaf.mode: DEBUG